# Generated by Django 3.1.5 on 2021-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_email', models.EmailField(blank=True, max_length=200)),
            ],
        ),
    ]
