# Generated by Django 3.1.5 on 2021-01-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20210116_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='2846', editable=False, max_length=4, unique=True),
        ),
    ]
