# Generated by Django 3.1.5 on 2021-01-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='9070', max_length=4, unique=True),
        ),
    ]
