# Generated by Django 3.1.5 on 2021-01-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20210116_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slots', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='7287', max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
                ('time_slots', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.timeslots')),
            ],
        ),
    ]
