# Generated by Django 3.1.5 on 2021-01-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20210117_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlots',
            new_name='TimeSlot',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='time_slots',
            new_name='time_slot',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='7709', max_length=4, unique=True),
        ),
    ]
