# Generated by Django 3.1.5 on 2021-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20210117_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='2838', max_length=4, unique=True),
        ),
    ]
