# Generated by Django 3.1.5 on 2021-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20210117_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday')], default=12, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='5562', max_length=4, unique=True),
        ),
    ]
